services:
  - type: web
    name: angular-signup-verification-frontend
    env: node
    buildCommand: cd angular-signup-verification-boilerplate && npm install && npm run build
    startCommand: cd angular-signup-verification-boilerplate && npx serve -s dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: API_URL
        value: https://angular-signup-verification-api.onrender.com

  - type: web
    name: angular-signup-verification-api
    env: node
    buildCommand: cd node-mysql-boilerplate-api && npm install
    startCommand: cd node-mysql-boilerplate-api && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: FRONTEND_URL
        value: https://angular-signup-verification-frontend.onrender.com
      - key: DB_HOST
        value: switchback.proxy.rlwy.net
      - key: DB_PORT
        value: 18439
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: mRRWKpCxvltpPLyjGHqTNREUuQeZbwPP
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false  # Add your Gmail address here
      - key: SMTP_PASS
        sync: false  # Add your Gmail app password here

databases:
  - name: postgres-db
    databaseName: railway
    user: postgres
    plan: free 