services:
  - type: web
    name: user-management-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist/user-management-system
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: API_URL
        value: https://user-management-api.onrender.com

  - type: web
    name: user-management-api
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: FRONTEND_URL
        value: https://user-management-frontend.onrender.com
      - key: DATABASE_URL
        value: ${{ Postgres-7Wqe.DATABASE_URL }}
      - key: JWT_SECRET
        value: "your-secret-key"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "christiandhave3@gmail.com"
      - key: SMTP_PASS
        value: "dkah vtre czrv atme"
      - key: EMAIL_FROM
        value: "christiandhave3@gmail.com"

databases:
  - name: postgres-db
    databaseName: railway
    user: postgres
    plan: free 